spring:
  profiles:
    active: local

spring:
  profiles:
    data:
      name: tcrmd00
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/tcrmd00
      driver: com.mysql.jdbc.Driver